name: ItemWorth
version: '${project.version}'
main: org.mrdarkimc.itemworth.ItemWorth
api-version: '1.19'
depend:
  - ProtocolLib
commands:
  worth:
    description: /worth usage
  setprice:
    description: /worth usage